project:
  type: website

website:
  title: "Simon Grendéus"
  site-url: asd
  description: "Blog about reptiles, reptile cognition, and evolution"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/grendeus
      - text: Bluesky
        href: https://bsky.app/profile/grendeus.bsky.social
format:
  html:
    theme: cosmo
    css: styles.css



